services:
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
      - '15672:15672'
  redis:
    image: redis:latest
    container_name: redis_mq
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "admin123" ]

